name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Start containers
      run: docker-compose -f deployment/docker-compose.yaml up -d

    - name: Wait for db ready
      uses: jakejarvis/wait-action@master
      with:
        time: '3m'

    - name: Run ut
      run: sh script/run_test.sh

    - name: Build
      run: go build -v ./...