name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Start containers
        run: docker-compose -f "./deployment/docker-compose.yml" up -d --build

    - name: Wait for db ready
      uses: jakejarvis/wait-action@master
        with:
          time: '3m'

    - name: Run ut

    - name: Build
      run: go build -v ./...